### PR TITLE
Show Ancient & Primal items in minimap & show text instead of icon in inventory

### PR DESCRIPTION
**Pull request by RevoLand**
Might be edited to let user have option on background color & text etc. 

Feel free to dismiss the pull request if you don't like, thanks for your effort.

### CODE REVIEW

**Comment by RevoLand** [comment]
Screenshots:
Inventory: https://dl.dropboxusercontent.com/s/013piwlbky5kc6n/18-Sunday-kf21Vv5H554.png
Minimap: https://dl.dropboxusercontent.com/s/nr6ogtatijjl39x/minimap.PNG

**Comment by Enigma32** [comment]
Too many changes not directly related to Ancient and Primal items.

**Comment by Enigma32** [comment]
Also, I don't agree with the visuals :) But thanks anyways.

**Comment by brusej** [comment]
I always appreciate your efforts. 
-----Original Message-----

**Pull request closed without merging**
