### PR TITLE
Update 32-bit symbols to 2.6.1.48432

### PR DESCRIPTION
**Pull request by ZenDraL**
Took the 32 bit offsets from here https://github.com/reks-scripts/D3Helper-Reks-MageMod

### CODE REVIEW

**Comment by Enigma32** [comment]
64-bit symbols still work with updated version? Otherwise the 64-bit symbol table should not have its version bumped.

**Comment by d2k2-git** [comment]
Yes the 64bit table is stll working

**Comment by ZenDraL** [comment]
Yeah they 64 bit symbols are fine. I didn't realize that the version number should not be bumped.

**Comment by Enigma32** [comment]
The commit comments were focusing on 32-bit, so just wanted to make sure the existing 64-bit symbols could still be used for that patch. If they would require changes, then version number should not be bumped. But since they're still compatible, bumping version number is fine :) Thanks.

**Pull request merged**
